name: fides
description: "A customer loyalty app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  result_dart: ^2.0.0
  uuid: ^4.5.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  flutter_layout_grid: ^2.0.8
  wolt_modal_sheet: ^0.11.0
  sentry_flutter: ^8.14.2
  flutter_dotenv: ^5.2.1
  currency_picker: ^2.0.21
  phone_form_field: ^10.0.2
  hugeicons: ^0.0.11
  beamer: ^1.7.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flex_color_scheme: ^8.2.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  objectbox_generator: any
  freezed: ^3.0.6

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Livvic-Thin.ttf
          weight: 100
        - asset: assets/fonts/Livvic-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Livvic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Livvic-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Livvic-Light.ttf
          weight: 300
        - asset: assets/fonts/Livvic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Livvic-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Livvic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Livvic-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Livvic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Livvic-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Livvic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Livvic-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Livvic-Black.ttf
          weight: 900

