import 'package:flutter/material.dart';

ColorScheme lightScheme() {
  return const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff744c90),
    surfaceTint: Color(0xff754e92),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff8e65ab),
    onPrimaryContainer: Color(0xfffffeff),
    secondary: Color(0xff884b65),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffdc94b0),
    onSecondaryContainer: Color(0xff622c44),
    tertiary: Color(0xff5d604d),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffebedd4),
    onTertiaryContainer: Color(0xff696b57),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfffff7fd),
    onSurface: Color(0xff1e1a1f),
    onSurfaceVariant: Color(0xff4b444f),
    outline: Color(0xff7d7480),
    outlineVariant: Color(0xffcec3d0),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff332f34),
    inversePrimary: Color(0xffe2b6ff),
    primaryFixed: Color(0xfff3daff),
    onPrimaryFixed: Color(0xff2d0349),
    primaryFixedDim: Color(0xffe2b6ff),
    onPrimaryFixedVariant: Color(0xff5c3678),
    secondaryFixed: Color(0xffffd9e5),
    onSecondaryFixed: Color(0xff380921),
    secondaryFixedDim: Color(0xfffdb1ce),
    onSecondaryFixedVariant: Color(0xff6c344d),
    tertiaryFixed: Color(0xffe2e4cc),
    onTertiaryFixed: Color(0xff1a1d0e),
    tertiaryFixedDim: Color(0xffc6c8b1),
    onTertiaryFixedVariant: Color(0xff454836),
    surfaceDim: Color(0xffe0d8de),
    surfaceBright: Color(0xfffff7fd),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfffaf1f8),
    surfaceContainer: Color(0xfff4ebf2),
    surfaceContainerHigh: Color(0xffeee6ec),
    surfaceContainerHighest: Color(0xffe8e0e7),
  );
}
